### ISSUE TITLE
[tip] module.css 활용

### ISSUE THREAD

**Issue by writer0713** [writer0713/react-study#7]
- 참고 : https://nomadcoders.co/react-for-beginners/lectures/3280
- `create-react-app` 으로 프로젝트를 구성한 경우, `xxx.module.css` 라는 명을 사용하여 css 파일을 생성하면 css를 모듈화 할 수 있다.

```jsx
# App.js

import ButtonA from './ButtonA';
import ButtonB from './ButtonB';

function App() {
  return (
    <div>
      <ButtonA />
      <ButtonB />
    </div>
  );
}

export default App;
```

```jsx
# ButtonA.js

import styles from './ButtonA.module.css';

const ButtonA = () => {
  return <button className={styles.btn}>button A</button>;
};

export default ButtonA;
```

```css
# ButtonA.module.css

.btn {
  background-color: orange;
  color: white;
}
```

```jsx
# ButtonB.js

import styles from './ButtonB.module.css';

const ButtonA = () => {
  return <button className={styles.btn}>button B</button>;
};

export default ButtonA;
```

```css
# ButtonB.module.css

.btn {
  background-color: green;
  color: white;
}
```

![스크린샷 2021-11-13 오후 2 14 43](https://user-images.githubusercontent.com/5811400/141606655-40a2dc28-e96b-4355-ae19-df37bc33f3b0.png)
